/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import Connection.LoadData;
import Connection.DataConnection;
import DbUtils.DbUtils;
import Model.KhuyenMai;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.CT_KhuyenMai;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author Admin
 */
public class GiaoDienKhuyenMai extends javax.swing.JFrame {

    /**
     * Creates new form KhuyenMai
     */
    private DefaultTableModel myTable;
    private DefaultTableModel myTable1;
    private DefaultTableModel myTable2;
    public GiaoDienKhuyenMai() {
        initComponents();
        myTable  = (DefaultTableModel) jTable1.getModel();
        myTable1 = (DefaultTableModel) jTable2.getModel();
        showData0();
        jTable1.setDefaultEditor(Object.class, null);;
        //jTable1.setSelectionBackground(Color.RED);
        jTable1.setSelectionMode(0);
        showData1();
        jTable2.setDefaultEditor(Object.class, null);;
        //jTable1.setSelectionBackground(Color.RED);
        jTable2.setSelectionMode(0);
    }
    private void showData0(){
         new LoadData();
        int dem = 0;
        myTable .setRowCount(0);
        for (KhuyenMai km : Controller.controller.arrayListKhuyenMai) {
            dem++;
            myTable .addRow(new Object[]{dem,km.getMaKM(),km.getMaNV(),km.getLyDoKM(),km.getNgayBD(),km.getNgayKT()});
        }
    }   
       
        
    private void showData1(){
        new LoadData();
        int dem1 = 0;
        myTable1.setRowCount(0);
        for(CT_KhuyenMai ctkm : Controller.controller.arrayListCT_KhuyenMai){
            dem1++;
            myTable1.addRow(new Object[] {dem1,ctkm.getMaKM(),ctkm.getMaDH(),ctkm.getPTKM()});
        }
    }
    private void showCTKM(){
        myTable2 = (DefaultTableModel) jTable2.getModel();
        new LoadData();
        int x = jTable1.getSelectedRow();
        int dem2 = 0;
        myTable2.setRowCount(0);
        String n = (String) myTable.getValueAt(x,1);
        for(CT_KhuyenMai ctkm : Controller.controller.arrayListCT_KhuyenMai){
            dem2++;
            if(ctkm.getMaKM().equals(n)){
            myTable1.addRow(new Object[] {dem2,ctkm.getMaKM(),ctkm.getMaDH(),ctkm.getPTKM()});
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        KM = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLyDo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dateNgayKT = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        baoloi = new javax.swing.JLabel();
        CTKM = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtCTKM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPTKM = new javax.swing.JTextField();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        baoloi1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHUYẾN MÃI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT KHUYẾN MÃI");

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        KM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KM", "Mã NV", "Lí do", "Ngày BD", "Ngày KT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã KM:");

        txtMaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã NV:");

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Lí do:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ngày BD:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngày KT:");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa ");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        baoloi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi.setForeground(new java.awt.Color(255, 51, 51));
        baoloi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baoloi.setText("Báo lỗi sẽ hiển thị ở đây...");

        javax.swing.GroupLayout KMLayout = new javax.swing.GroupLayout(KM);
        KM.setLayout(KMLayout);
        KMLayout.setHorizontalGroup(
            KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KMLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(KMLayout.createSequentialGroup()
                                        .addComponent(dateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                    .addComponent(txtLyDo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaKM, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KMLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KMLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)))))
                .addGap(10, 10, 10))
        );
        KMLayout.setVerticalGroup(
            KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(dateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        CTKM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã KM", "Mã DH", "PTKM (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã KM:");

        txtCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTKMActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mã DH:");

        txtMaDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDHActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Phần trăm khuyến mãi:");

        txtPTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTKMActionPerformed(evt);
            }
        });

        btnThem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem1.setText("Thêm ");
        btnThem1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa1.setText("Xóa ");
        btnXoa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnreset1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnreset1.setText("Reset");
        btnreset1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        baoloi1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi1.setForeground(new java.awt.Color(255, 51, 51));
        baoloi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baoloi1.setText("Báo lỗi sẽ hiện thị ở đây...");

        javax.swing.GroupLayout CTKMLayout = new javax.swing.GroupLayout(CTKM);
        CTKM.setLayout(CTKMLayout);
        CTKMLayout.setHorizontalGroup(
            CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKMLayout.createSequentialGroup()
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTKMLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CTKMLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CTKMLayout.createSequentialGroup()
                                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CTKMLayout.createSequentialGroup()
                                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))
                                    .addGroup(CTKMLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPTKM))
                                    .addGroup(CTKMLayout.createSequentialGroup()
                                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(38, 38, 38)
                                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaDH, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                            .addComponent(txtCTKM))))
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addComponent(baoloi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        CTKMLayout.setVerticalGroup(
            CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKMLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(baoloi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(CTKMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(home)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(KM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(home)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(KM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKMActionPerformed

    private void txtCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTKMActionPerformed

    private void txtMaDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDHActionPerformed

    private void txtPTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTKMActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
        if(txtMaKM.getText().equals("") || txtMaNV.getText().equals("") || txtLyDo.getText().equals("") ||dateNgayBD.getDate().equals("") || dateNgayKT.getDate().equals(""))
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin khuyến mãi!"); 
        else{
            
            int row = jTable1.getSelectedRow();
            KhuyenMai km = new KhuyenMai(txtMaKM.getText(), txtMaNV.getText(), txtLyDo.getText(), dateNgayBD.getDate(),dateNgayKT.getDate());
           if (jTable1.getSelectedRow()==-1){
            
                for (KhuyenMai kmm : Controller.controller.arrayListKhuyenMai)
                    if(kmm.getMaKM().equals(txtMaKM.getText())){
                        baoloi.setText("Mã khuyến mãi đã tồn tại!");
                        return;
                    }
                Connection.InsertData.insertKhuyenMai(km);
                
                showData0();


                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount()-1,jTable1.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updateKhuyenMai(km);
               
           }
           showData0();
            //showData();
           jTable1.getSelectionModel().setSelectionInterval(row, row);
        } 
        String x = "";
        txtMaKM.setText(x);
        txtMaNV.setText(x);
        txtLyDo.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
         if(txtCTKM.getText().equals("") || txtMaDH.getText().equals("") || txtPTKM.getText().equals(""))
                 baoloi1.setText("Vui lòng nhập đầy đủ thông tin chi tiết khuyến mãi!");
        else{
            
            int row = jTable2.getSelectedRow();
            int PTKM = Integer.parseInt(txtPTKM.getText());
            CT_KhuyenMai ctkm = new CT_KhuyenMai(txtCTKM.getText(),txtMaDH.getText(),PTKM);
           if (jTable2.getSelectedRow()==-1){
            
                //for (CT_KhuyenMai ctkmm : Controller.controller.arrayListCT_KhuyenMai)
 
                Connection.InsertData.insertCT_KhuyenMai(ctkm);
                
                
                showData1();


                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount()-1,jTable2.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updateCT_KhuyenMai(ctkm);
               
           }
           showData1();
           jTable2.getSelectionModel().setSelectionInterval(row, row);
        }    
            String x = "";
        txtCTKM.setText(x);
        txtMaDH.setText(x);
        txtPTKM.setText(x);
        txtCTKM.setEnabled(true);
        btnThem1.setEnabled(true);
        showData1();         // TODO add your handling code here:
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         if(jTable1.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn khuyến mãi");}
        else
        {
          int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Xóa Khuyến Mãi?", "Xác nhận",JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    System.out.println( jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                    Connection.DeleteData.deleteKhuyenMai((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                      showData0();
                } 
        }   
         String x = "";
        txtMaKM.setText(x);
        txtMaNV.setText(x);
        txtLyDo.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        if(jTable2.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn chi tiết khuyến mãi");}
        else
        {
          int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Xóa Chi Tiết Khuyến Mãi?", "Xác nhận",JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    System.out.println( jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                    Connection.DeleteData.delelteCT_KhuyenMai((String) jTable2.getValueAt(jTable2.getSelectedRow(), 2));
                      showData1();
                } 
        }     
        String x = "";
        txtCTKM.setText(x);
        txtMaDH.setText(x);
        txtPTKM.setText(x);
        txtCTKM.setEnabled(true);
        btnThem1.setEnabled(true);
        showData1();
// TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        btnThem.setEnabled(false);
        txtMaKM.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row= jTable1.getSelectedRow();
        txtMaKM.setText((String) jTable1.getValueAt(row,1));
        txtMaNV.setText((String) jTable1.getValueAt(row,2));
        txtLyDo.setText((String) jTable1.getValueAt(row,3));
        String datebd =  jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString(); 
        String datekt =  jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        datebd=datebd.substring(8,10)+"/"+datebd.substring(5,7)+"/"+datebd.substring(0,4);
        datekt=datekt.substring(8,10)+"/"+datekt.substring(5,7)+"/"+datekt.substring(0,4);

        try {
            java.util.Date  datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(datebd);
             dateNgayBD.setDate(datetmp);
             java.util.Date  datetmp1 = new SimpleDateFormat("dd/MM/yyyy").parse(datekt);
             dateNgayKT.setDate(datetmp1);
         } catch (ParseException ex) {
             Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
         }   
        if(evt.getClickCount()==2){
            jTable2.setDefaultEditor(Object.class, null);
            //jTable1.setSelectionBackground(Color.RED);
            jTable2.setSelectionMode(0);
              showCTKM();
         }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        btnThem1.setEnabled(false);
        txtCTKM.setEnabled(false);
        txtMaDH.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row= jTable2.getSelectedRow();
        txtCTKM.setText((String) jTable2.getValueAt(row,1));
        txtMaDH.setText((String) jTable2.getValueAt(row,2));   
        txtPTKM.setText(jTable2.getValueAt(row, 3).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    if(txtMaKM.getText().equals("") || txtMaNV.getText().equals("") || txtLyDo.getText().equals("") ||dateNgayBD.getDate().equals("") || dateNgayKT.getDate().equals(""))
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin khuyến mãi!"); 
        else{
            
            int row = jTable1.getSelectedRow();
            KhuyenMai km = new KhuyenMai(txtMaKM.getText(), txtMaNV.getText(), txtLyDo.getText(), dateNgayBD.getDate(),dateNgayKT.getDate());
           if (jTable1.getSelectedRow()==-1){
            
                for (KhuyenMai kmm : Controller.controller.arrayListKhuyenMai)
                    if(kmm.getMaKM().equals(txtMaKM.getText())){
                        baoloi.setText("Mã khuyến mãi đã tồn tại!");
                        return;
                    }

             }
            else
           {
                
                Connection.UpdateData.updateKhuyenMai(km);
               
           }
           showData0();
           //showData();
           jTable1.getSelectionModel().setSelectionInterval(row, row);
        }   
        String x = "";
        txtMaKM.setText(x);
        txtMaNV.setText(x);
        txtLyDo.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        showData0();
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
     if(txtCTKM.getText().equals("") || txtMaDH.getText().equals("") || txtPTKM.getText().equals(""))
                 baoloi1.setText("Vui lòng nhập đầy đủ thông tin chi tiết khuyến mãi!");
        else{
            
            int row = jTable2.getSelectedRow();
            int PTKM = Integer.parseInt(txtPTKM.getText());
            CT_KhuyenMai ctkm = new CT_KhuyenMai(txtCTKM.getText(),txtMaDH.getText(),PTKM);

               
               for(CT_KhuyenMai ctkmm : Controller.controller.arrayListCT_KhuyenMai)
                   if(PTKM >100){
                       baoloi.setText("Phần trăm khuyến mãi < 100");
                   }else{
                    String x = "";
                    txtCTKM.setText(x);
                    txtMaDH.setText(x);
                    txtPTKM.setText(x);
                    txtCTKM.setEnabled(true);
                    btnThem1.setEnabled(true);
                    txtMaDH.setEnabled(true);
                
                Connection.UpdateData.updateCT_KhuyenMai(ctkm);            
                
                break;
                   }
                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount()-1,jTable2.getRowCount()-1);
                showData1();
             


   
           
          //showData1();
          // jTable2.getSelectionModel().setSelectionInterval(row, row);
        }      

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DataConnection.createStatement();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String jdate = date.format(dateNgayBD.getDate());
        String jdate1 = date.format(dateNgayKT.getDate());
        
            try {
                String sql = ("select * from dbo.KhuyenMai where NgayBD >= '" + jdate + "' and NgayKT <='" + jdate1 + "'");
                PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Trang_Chinh().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        String x = "";
        txtMaKM.setText(x);
        txtMaNV.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        txtLyDo.setText(x);
        showData0();
// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        String x = "";
        txtCTKM.setText(x);
        txtMaDH.setText(x);
        txtPTKM.setText(x);
        txtCTKM.setEnabled(true);
        btnThem1.setEnabled(true);
        showData1();
// TODO add your handling code here:
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienKhuyenMai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CTKM;
    private javax.swing.JPanel KM;
    private javax.swing.JLabel baoloi;
    private javax.swing.JLabel baoloi1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private com.toedter.calendar.JDateChooser dateNgayBD;
    private com.toedter.calendar.JDateChooser dateNgayKT;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCTKM;
    private javax.swing.JTextField txtLyDo;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtPTKM;
    // End of variables declaration//GEN-END:variables
}
