/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;
import java.sql.PreparedStatement;
import Connection.DataConnection;
import DbUtils.DbUtils;
import Connection.LoadData;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.CT_PhieuBaoHanh;
import Model.CT_PhieuDat;
import Model.NhanVien;
import Model.PhieuBaoHanh;
import Model.TaiKhoan;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.Date;
import java.sql.ResultSet;
import javax.swing.Action;
/**
 *
 * @author Admin
 */
public class GiaoDienBaoHanh extends javax.swing.JFrame {

    /**
     * Creates new form BaoHanh
     */
    private DefaultTableModel myTable;
    private DefaultTableModel myTable1;
    private DefaultTableModel myTable2;
    public GiaoDienBaoHanh() { 
        
        initComponents();
        myTable  = (DefaultTableModel) jTable1.getModel();
        myTable1 = (DefaultTableModel) jTable2.getModel();
        myTable2 = (DefaultTableModel) jTable2.getModel();
        
        jTable1.setDefaultEditor(Object.class, null);
        //jTable1.setSelectionBackground(Color.RED);
        jTable1.setSelectionMode(0);
        
        
        if(Controller.controller.tk.getLoaiTaiKhoan().equals("Quản lý")  ){
            btnXoa1.setEnabled(true);
            btnSua1.setEnabled(true);
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            showData();showData1();
            
        }else {
             btnXoa1.setEnabled(true);
            btnSua1.setEnabled(true);
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            showData();showData1();
            
            }

       
        
        
    
    }
    private void showData(){
        new LoadData();
        int dem = 0;
        myTable .setRowCount(0);
        for (PhieuBaoHanh bh : Controller.controller.arrayListPhieuBaoHanh) {
            dem++;
           myTable .addRow(new Object[]{dem,bh.getMaPBH(),bh.getMaDH(),bh.getNgayBD(),bh.getNgayKT()});
    }   
         
}   
 
    private void showData1(){
        new LoadData();
        int dem1 = 0;
        
        myTable1.setRowCount(0);
        for(CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh){
            dem1++;
            myTable1.addRow(new Object[] {dem1,ctbh.getMaPBH(),ctbh.getMaNV(),ctbh.getTrangThai()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPBH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCTBH = new javax.swing.JTextField();
        txtMNV = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTT = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        dateBD = new com.toedter.calendar.JDateChooser();
        dateKT = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtMDH = new javax.swing.JTextField();
        baoloi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU BẢO HÀNH");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu bảo hành", "Mã đồng hồ", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT PHIẾU BẢO HÀNH");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu bảo hành", "Trạng thái", "Mã nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã phiếu bảo hành:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ngày BD:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày KT:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mã phiếu bảo hành:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Trạng Thái:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mã nhân viên:");

        txtMNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNVActionPerformed(evt);
            }
        });

        txtTT.setColumns(20);
        txtTT.setRows(5);
        jScrollPane3.setViewportView(txtTT);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem1.setText("Thêm ");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa1.setText("Xóa ");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mã đồng hồ:");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dateBD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dateKT, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                            .addComponent(txtPBH)
                                            .addComponent(txtMDH)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3)
                                            .addComponent(txtMNV)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCTBH)))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnThem1)
                                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTim)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnXoa1)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSua1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1)))))
                                .addGap(49, 49, 49))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dateKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem1)
                            .addComponent(btnXoa1)
                            .addComponent(btnSua1)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTim)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCTBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(jButton2))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void LayCT(){
        myTable2 = (DefaultTableModel) jTable2.getModel();
        new LoadData();
        int dem2 = 0;
        int x = jTable1.getSelectedRow();
        myTable2.setRowCount(0);
        String n = (String) myTable.getValueAt(x,1);
        for(CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh){
                dem2++;
                if(ctbh.getMaPBH().equals(n)){
                    jTable2.removeAll();
                    myTable2.addRow(new Object[] {dem2,ctbh.getMaPBH(),ctbh.getMaNV(),ctbh.getTrangThai()});
                }    
            
        }
    }
    private void txtMNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNVActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         if(txtCTBH.getText().equals("") ||txtTT.getText().equals("") ||txtMNV.getText().equals("") )
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin chi tiết phiếu bảo hành!");
        else{
            
            int row = jTable2.getSelectedRow();
           CT_PhieuBaoHanh ctph = new CT_PhieuBaoHanh(txtCTBH.getText(), txtTT.getText(), txtMNV.getText());
           if (jTable2.getSelectedRow()==-1){
            
                for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh)
                    if(ctbh.getMaPBH().equals(txtCTBH.getText())){
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                Connection.InsertData.insertCT_BaoHanh(ctph);

                
                showData1();


                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount()-1,jTable2.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updateCT_PhieuBaoHanh(ctph);
                
           }
           showData1();
          
        }   
      String y ="";
      txtCTBH.setText(y);
      txtMNV.setText(y);
      txtTT.setText(y);
      txtCTBH.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed

        if(txtPBH.getText().equals("") ||txtMDH.getText().equals("") || dateBD.getDate().equals("") || dateKT.getDate().equals("") )
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin phiếu bảo hành!");
        else{
            
            int row = jTable1.getSelectedRow();
            PhieuBaoHanh bh = new PhieuBaoHanh(txtPBH.getText(), txtMDH.getText(), dateBD.getDate(), dateKT.getDate());
           if (jTable1.getSelectedRow()==-1){
            
                for (PhieuBaoHanh bhh : Controller.controller.arrayListPhieuBaoHanh)
                    if(bhh.getMaPBH().equals(txtPBH.getText())){
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                Connection.InsertData.insertPhieuBaoHanh(bh);

                
                showData();


                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount()-1,jTable1.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updatePhieuBaoHanh(bh);
               
           }
           showData();
           jTable1.getSelectionModel().setSelectionInterval(row, row);
        }      
        String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        dateBD.setDate(null);
        dateKT.setDate(null);
        txtPBH.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        jTable1.setModel(myTable);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        txtPBH.setEnabled(true);
        jTable1.setModel(myTable);
        showData();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String y ="";
      txtCTBH.setText(y);
      txtMNV.setText(y);
      txtTT.setText(y);
       txtCTBH.setEnabled(true);
       jTable2.setModel(myTable1);
        showData1();
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed

            Xoa();
            String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        dateBD.setDate(null);
        dateKT.setDate(null);
        txtPBH.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        jTable1.setModel(myTable);
              // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed
    private void Xoa(){
        if(jTable1.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn phiếu bảo hành");}
        else
        {
          int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Xóa Phiếu Bảo Hành?", "Xác nhận",JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    System.out.println( jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                    Connection.DeleteData.deleteBaoHanh((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                      showData();
                      showData1();
                } 
        }               
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    if(jTable2.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn chi tiết bảo hành");}
        else
        {
          int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Xóa Chi Tiết Bảo Hành?", "Xác nhận",JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    System.out.println( jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                    Connection.DeleteData.deleteCT_PhieuBaoHanh((String) jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                      showData1();
                } 
        }   
      String y ="";
      txtCTBH.setText(y);
      txtMNV.setText(y);
      txtTT.setText(y);
       txtCTBH.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        btnSua1.setEnabled(true);
        baoloi.setText("");// TODO add your handling code here:
        int row= jTable1.getSelectedRow();
        txtPBH.setText((String) jTable1.getValueAt(row,1));
        txtMDH.setText((String) jTable1.getValueAt(row,2));
        String datebd =  jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString(); 
        String datekt =  jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        datebd=datebd.substring(0,4)+"/"+datebd.substring(5,7)+"/"+datebd.substring(8,10);
        datekt=datekt.substring(0,4) + "/"+datekt.substring(5,7)+"/"+datekt.substring(8,10);

        try {
            java.util.Date  datetmp = new SimpleDateFormat("yyyy/MM/dd").parse(datebd);
             dateBD.setDate(datetmp);
             java.util.Date  datetmp1 = new SimpleDateFormat("yyyy/MM/dd").parse(datekt);
             dateKT.setDate(datetmp1);
         } catch (ParseException ex) {
             Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
         }
         txtPBH.setEnabled(false);
         if(evt.getClickCount()==2){
            jTable2.setDefaultEditor(Object.class, null);
            //jTable1.setSelectionBackground(Color.RED);
            jTable2.setSelectionMode(0);
             LayCT();
         }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (jTable1.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn phiếu bảo hành");
            }  
             else if(txtPBH.getText().equals("") ||txtMDH.getText().equals("") || dateBD.getDate().equals("") || dateKT.getDate().equals("") )
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin phiếu bảo hành!");
        else{

            txtPBH.setEnabled(false);
            int row = jTable1.getSelectedRow();
            
            PhieuBaoHanh bh = new PhieuBaoHanh(txtPBH.getText(), txtMDH.getText(), dateBD.getDate(), dateKT.getDate());
            
        if(jTable1.getSelectedRow()==-1)
            {
                for (PhieuBaoHanh bhh : Controller.controller.arrayListPhieuBaoHanh)
                    if(bhh.getMaPBH().equals(txtPBH.getText())){
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                Connection.InsertData.insertPhieuBaoHanh(bh);

                
                showData();


                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount()-1,jTable1.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updatePhieuBaoHanh(bh);
               
           }
           showData();
           jTable1.getSelectionModel().setSelectionInterval(row, row);
  // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed
   }
    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        txtCTBH.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row= jTable2.getSelectedRow();
        txtCTBH.setText((String) jTable2.getValueAt(row,1));
        txtTT.setText((String) jTable2.getValueAt(row,2));  
        txtMNV.setText((String) jTable2.getValueAt(row,3));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         if (jTable2.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn chi tiết phiếu bảo hành");
        }
         else if(txtCTBH.getText().equals("") ||txtTT.getText().equals("") ||txtMNV.getText().equals("") )
                 baoloi.setText("Vui lòng nhập đầy đủ thông tin chi tiết phiếu bảo hành!");
        else{
            
            int row = jTable2.getSelectedRow();
           CT_PhieuBaoHanh ctph = new CT_PhieuBaoHanh(txtCTBH.getText(), txtTT.getText(), txtMNV.getText());
        if(jTable2.getSelectedRow()==-1)
           
                {
            
                for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh)
                    if(ctbh.getMaPBH().equals(txtCTBH.getText())){
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                Connection.InsertData.insertCT_BaoHanh(ctph);

                
                showData1();


                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount()-1,jTable2.getRowCount()-1);

             }
            else
           {
                
                Connection.UpdateData.updateCT_PhieuBaoHanh(ctph);
                
           }
           showData1();
          jTable2.getSelectionModel().setSelectionInterval(row, row);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

        DataConnection.createStatement();
        dateBD.disable();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
         String jdate = date.format(dateBD.getDate());
         String jdate1  = date.format(dateKT.getDate());
        
            try {
                String sql = ("select * from dbo.BaoHanh where NgayBD >= '" + jdate + "' and NgayKT <='" + jdate1 + "'");
                PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
            }

         
    }//GEN-LAST:event_btnTimActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Trang_Chinh().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienBaoHanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoloi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private com.toedter.calendar.JDateChooser dateBD;
    private com.toedter.calendar.JDateChooser dateKT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCTBH;
    private javax.swing.JTextField txtMDH;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextField txtPBH;
    private javax.swing.JTextArea txtTT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
